name: 'Hive tests'

on:
  push:
    tags: ['*']
  workflow_dispatch:

jobs:
  stCreate2:
    name: stCreate2
    runs-on: ubuntu-latest
    steps:
      - name: Set up parameters
        run: |
          echo "LOG_LEVEL=${{ github.event.inputs.log-level || '3' }}" >> $GITHUB_ENV
          echo "HIVE_REPO=${{ github.event.inputs.hive-repo || 'ethereum/hive' }}" >> $GITHUB_ENV
          echo "HIVE_BRANCH=${{ github.event.inputs.hive-branch || 'master' }}" >> $GITHUB_ENV
      - name: Check out Nethermind repository
        uses: actions/checkout@v3
        with:
          path: nethermind
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: nethermind
          file: nethermind/Dockerfile
          tags: nethermind:test-${{ github.sha }}
          outputs: type=docker,dest=/tmp/image.tar
      - name: Install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential
      - name: Set up Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '>=1.17.0'
      - name: Check out Hive repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.HIVE_REPO }}
          ref: ${{ env.HIVE_BRANCH }}
          path: hive
      - name: Patch Hive Dockerfile
        run: sed -i 's#FROM nethermindeth/hive:$branch#FROM nethermind:test-${{ github.sha }}#g' hive/clients/nethermind/Dockerfile
      - name: Build Hive
        working-directory: hive
        run: go build .
      - name: Load Docker image
        run: docker load --input /tmp/image.tar
      - name: Run Hive
        continue-on-error: true
        working-directory: hive
        run: ./hive --client nethermind --sim ethereum/consensus --sim.loglevel $LOG_LEVEL --sim.limit /stCreate2 --sim.parallelism 16
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: results-stCreate2-${{ github.run_number }}-${{ github.run_attempt }}
          path: hive/workspace
          retention-days: 7
      - name: Print results
        run: |
          chmod +x nethermind/scripts/hive-results.sh
          nethermind/scripts/hive-results.sh "hive/workspace/logs/*.json"
  bcUncleTest:
      name: bcUncleTest
      runs-on: ubuntu-latest
      steps:
          - name: Set up parameters
            run: |
                echo "LOG_LEVEL=${{ github.event.inputs.log-level || '3' }}" >> $GITHUB_ENV
                echo "HIVE_REPO=${{ github.event.inputs.hive-repo || 'ethereum/hive' }}" >> $GITHUB_ENV
                echo "HIVE_BRANCH=${{ github.event.inputs.hive-branch || 'master' }}" >> $GITHUB_ENV
          - name: Check out Nethermind repository
            uses: actions/checkout@v3
            with:
                path: nethermind
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Build Docker image
            uses: docker/build-push-action@v3
            with:
                context: nethermind
                file: nethermind/Dockerfile
                tags: nethermind:test-${{ github.sha }}
                outputs: type=docker,dest=/tmp/image.tar
          - name: Install Linux packages
            run: |
                sudo apt-get update
                sudo apt-get install libsnappy-dev libc6-dev libc6 build-essential
          - name: Set up Go environment
            uses: actions/setup-go@v3.0.0
            with:
                go-version: '>=1.17.0'
          - name: Check out Hive repository
            uses: actions/checkout@v3
            with:
                repository: ${{ env.HIVE_REPO }}
                ref: ${{ env.HIVE_BRANCH }}
                path: hive
          - name: Patch Hive Dockerfile
            run: sed -i 's#FROM nethermindeth/hive:$branch#FROM nethermind:test-${{ github.sha }}#g' hive/clients/nethermind/Dockerfile
          - name: Build Hive
            working-directory: hive
            run: go build .
          - name: Load Docker image
            run: docker load --input /tmp/image.tar
          - name: Run Hive
            continue-on-error: true
            working-directory: hive
            run: ./hive --client nethermind --sim ethereum/consensus --sim.loglevel $LOG_LEVEL --sim.limit /bcUncleTest --sim.parallelism 16
          - name: Upload results
            uses: actions/upload-artifact@v3
            with:
                name: results-bcUncleTest-${{ github.run_number }}-${{ github.run_attempt }}
                path: hive/workspace
                retention-days: 7
          - name: Print results
            run: |
                chmod +x nethermind/scripts/hive-results.sh
                nethermind/scripts/hive-results.sh "hive/workspace/logs/*.json"
